image: gitpod/workspace-flutter

tasks:
  - command: flutter run --web-port 8686
  - command: chromium-browser --no-sandbox

ports:
  - port: 8686
    onOpen: open-preview
  - port: 6080
    onOpen: open-preview
  - port: 5900
    onOpen: ignore
  - port: 35900
    onOpen: ignore

vscode:
  extensions:
    - Dart-Code.flutter@3.8.1:cytqQi/+kpu802ZOaJwayw==
    - Dart-Code.dart-code@3.8.1:+5Rq24Mq46eJa5w39WY0bA==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==