image: gitpod/workspace-flutter

tasks:
  - command: flutter run --web-port 8686

ports:
  - port: 8686
    onOpen: open-preview

vscode:
  extensions:
    - Dart-Code.flutter@3.8.1:cytqQi/+kpu802ZOaJwayw==
    - Dart-Code.dart-code@3.8.1:+5Rq24Mq46eJa5w39WY0bA==
    - esbenp.prettier-vscode@3.20.0:37/f4uBlE287wUjENFq1aA==